test_dataset:
  path: /Users/pierclgr/PycharmProjects/ML4CV/data/Set5/
  shuffle: false
  num_workers: 1
  pin_memory: true
  batch_size: 1
  degradation: bicubic
  scale: 2
testing:
  mode: model
  model: MultiPathResidualNetwork
  model_folder: /Users/pierclgr/PycharmProjects/ML4CV/trained_models/
  output_model_file: mprnet_final_model
wandb:
  logging: false # true
  run_name: Test_MPRNet_Set5
  project_name: ML4CV_project
  entity_name: pierclgr
  n_images_to_log: 3
seed: 1507
image_channels: 3